FinalProjects/Project1/Derivacion Completa/FutureAgro/Controllers/ModulosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FutureAgro.DataAccess.Data;
using FutureAgro.DataAccess.Models;
using FutureAgro.Web.Models;

namespace FutureAgro.Web.Controllers
{
    public class ModulosController : Controller
    {
        private readonly FutureAgroIdentityDbContext _context;

        public ModulosController(FutureAgroIdentityDbContext context)
        {
            _context = context;
        }

        // GET: Modulos
        public async Task<IActionResult> Index()
        {
            /*B-ModulosControllerIndex*/

/*Code injected by: ControlAmbienteBase_ModulosControllerDetalle*/
CargarLimites();
/*Code injected by: ControlAmbienteBase_ModulosControllerDetalle*/

            return View(await _context.Modulos.Include(modulo => modulo.Plantas).ToListAsync());
        }

        // GET: Modulos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            /*B-ModulosControllerDetalle*/

/*Code injected by: ControlAmbienteBase_ModulosControllerDetalle*/
CargarLimites();
/*Code injected by: ControlAmbienteBase_ModulosControllerDetalle*/

            
            var modulo = await _context.Modulos
                .Include(mod => mod.Plantas)
                .ThenInclude(planta => planta.Tipo)
                .FirstOrDefaultAsync(m => m.IdModulo == id);

            if (modulo == null)
            {
                return NotFound();
            }

            return View(modulo);
        }
        
        /*B-MetodosModulosController*/

/*Code injected by: ControlAmbienteBase_MetodosModulosController*/
// GET: Modulos/Ambiente/5
		public async Task<IActionResult> Ambiente(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var modulo = await _context.Modulos
				.FirstOrDefaultAsync(m => m.IdModulo == id);

			var medidasModulo = _context.Medidas
							.Where(r => r.IdModulo == id);

			/*B-ChartsControllerDetalle*/

/*Code injected by: LecturaTemp_ChartsControllerDetalle*/
ChartData datosTemperatura = ObtenerDatosMedida(medidasModulo, TipoMedida.Temperatura, "IndianRed", "AntiqueWhite");
        ViewData["DatosTemperatura"] = datosTemperatura;
/*Code injected by: LecturaTemp_ChartsControllerDetalle*/


/*Code injected by: LecturaHum_ChartsControllerDetalle*/
ChartData datosHumedad = ObtenerDatosMedida(medidasModulo, TipoMedida.Humedad, "#007bff", "LightBlue");
        ViewData["DatosHumedad"] = datosHumedad;
/*Code injected by: LecturaHum_ChartsControllerDetalle*/


/*Code injected by: LecturaLum_ChartsControllerDetalle*/
ChartData datosLuminosidad = ObtenerDatosMedida(medidasModulo, TipoMedida.Luminosidad, "Yellow", "LightYellow");
		ViewData["DatosLuminosidad"] = datosLuminosidad;
/*Code injected by: LecturaLum_ChartsControllerDetalle*/


			if (modulo == null)
			{
				return NotFound();
			}

			return View(modulo);
		}

		private static ChartData ObtenerDatosMedida(IQueryable<Medida> medidasModulo, TipoMedida tipoMedida, string color, string backgroundColor)
		{
			var medidas = medidasModulo
											.Where(r => r.TipoMedida == tipoMedida)
											.OrderByDescending(r => r.Fecha)
											.Take(10);

			var datosmedida = new ChartData()
			{
				Labels = medidas.Select(r => r.Fecha.ToLongTimeString()).ToArray(),
				Datasets = new ChartDataSet[] {
					new ChartDataSet()
					{
						Label = tipoMedida.ToString(),
						BackgroundColor = backgroundColor,
						BorderColor = color,
						BorderWidth = 1,
						PointBackgroundColor = color,
						Data = medidas.Select(r => r.Valor).ToArray()
					}
				}
			};
			return datosmedida;
		}

		private void CargarLimites()
		{
			/*BCP-CustomizationPoint */

			ViewData["TemperaturaLimiteSuperior"] = (double)22;
			ViewData["TemperaturaLimiteInferior"] = (double)18;
			ViewData["HumedadLimiteSuperior"] = 75;
			ViewData["HumedadLimiteInferior"] = 50;
			ViewData["LuminosidadLimiteSuperior"] = 700;
			ViewData["LuminosidadLimiteInferior"] = 450;

			/*ECP-CustomizationPoint */
		}
/*Code injected by: ControlAmbienteBase_MetodosModulosController*/


        // GET: Modulos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Modulos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdModulo,Capacidad")] Modulo modulo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(modulo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(modulo);
        }

        // GET: Modulos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modulo = await _context.Modulos.FindAsync(id);
            if (modulo == null)
            {
                return NotFound();
            }
            return View(modulo);
        }

        // POST: Modulos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdModulo,Capacidad")] Modulo modulo)
        {
            if (id != modulo.IdModulo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(modulo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuloExists(modulo.IdModulo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(modulo);
        }

        // GET: Modulos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modulo = await _context.Modulos
                .Include(mod => mod.Plantas)
                .FirstOrDefaultAsync(m => m.IdModulo == id);
            if (modulo == null)
            {
                return NotFound();
            }

            return View(modulo);
        }

        // POST: Modulos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var modulo = await _context.Modulos.FindAsync(id);
            _context.Modulos.Remove(modulo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModuloExists(int id)
        {
            return _context.Modulos.Any(e => e.IdModulo == id);
        }
    }
}

FinalProjects/Project1/Derivacion Completa/FutureAgro/Controllers/PrivacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FutureAgro.Web.Controllers
{
    [AllowAnonymous]
    public class PrivacyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FinalProjects/Project1/Derivacion Completa/FutureAgro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--BCP-CPTitulo-->
    <title>@ViewData["Title"] - FutureAgro Derivacion Completa</title>
    <!--ECP-CPTitulo-->
    <link src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue-indigo.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css?v=1.1" />

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">FutureAgro.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @Html.ActionLink("Home", "", "", new { }, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Módulos", "Index", "Modulos", new { }, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Plantas", "Index", "Plantas", new { }, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Privacidad", "Index", "Privacy", new { }, new { @class = "nav-link text-dark" })
                        </li>
                    </ul>
                </div>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse float-right">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i></a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <div class="media m-4">
                                    <!--B-FotoUsuario-->

<!--Code replaced by: Google_FotoUsuario-->
@{
		var picture = Context.User.Claims.FirstOrDefault(r => r.Type == "urn:google:picture")?.Value;
    }
    @if (!string.IsNullOrWhiteSpace(picture))
    {
		<img class="mr-2 rounded-circle" src="@picture" width="60" height="60" />
    }
    else
    {
		<i class="fas fa-user mr-3"></i>
    }
<!--Code replaced by: Google_FotoUsuario-->
<!--E-FotoUsuario-->
                                    <div class="media-body">
                                        <h6 class="media-title text-nowrap small mt-1">@Context.User.Identity.Name</h6>
                                    </div>
                                </div>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="/Account/Logout">Salir</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - FutureAgro.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

FinalProjects/Project1/Derivacion Completa/FutureAgro/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FutureAgro.Web</title>


    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue-indigo.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" rel="stylesheet">
</head>
<body>
    <header></header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3 pt-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - FutureAgro.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>